### ISSUE TITLE
This item isn't working?

### ISSUE THREAD

**Issue by ArvickC** [Yamakaja/commanditems#18]
CommonPick:
    item:
      type: CHEST
      name: "&7&lRandom Stone Tool"
      lore: ["&6Right Click&b to claim tool!"]
      glow: true
    consumed: true
    cooldown: 1
    actions:
      - { action: COMMAND, by: CONSOLE, command: "give {player} stone_pickaxe{Enchantments:[{id:efficiency,lvl:3},{id:unbreaking,lvl:1}]} 1" }
      - { action: MESSAGE, to: PLAYER, message: "&6You got:&a&l Common&7 Stone&a Pickaxe!" }

**Comment by Yamakaja** [comment]
Could you please provide me with an error message or some indication as to what has gone wrong?

In the meantime, try if this works:

```
CommonPick:
  item:
  type: CHEST
  name: "&7&lRandom Stone Tool"
  lore: ["&6Right Click&b to claim tool!"]
  glow: true
  consumed: true
  cooldown: 1
  actions:
   - { action: COMMAND, by: CONSOLE, command: 'give {player} stone_pickaxe\{Enchantments:[\{id:efficiency,lvl:3},\{id:unbreaking,lvl:1}]} 1' }
   - { action: MESSAGE, to: PLAYER, message: '&6You got:&a&l Common&7 Stone&a Pickaxe!' }
```

**Comment by ArvickC** [comment]
Error without the change you pasted: https://hastebin.com/alexaziqoy.apache

Error with the change you pasted: 
![image](https://user-images.githubusercontent.com/69405114/91414667-bd7e3e00-e801-11ea-95a5-158ec88f78c6.png)

**Comment by Yamakaja** [comment]
Ahh yes, the indentation is wrong - how about this:

```
CommonPick:
  item:
    type: CHEST
    name: "&7&lRandom Stone Tool"
    lore: ["&6Right Click&b to claim tool!"]
    glow: true
  consumed: true
  cooldown: 1
  actions:
   - { action: COMMAND, by: CONSOLE, command: 'give {player} stone_pickaxe\{Enchantments:[\{id:efficiency,lvl:3},\{id:unbreaking,lvl:1}]} 1' }
   - { action: MESSAGE, to: PLAYER, message: '&6You got:&a&l Common&7 Stone&a Pickaxe!' }
```
